# Theme Configuration
# Source: https://github.com/hehehai/hexo-theme-void

# header nav
menu:
    Home: /
    Archive: /archives/
    Rss: /atom.xml

# footer nav
social:
    Twitter: https://twitter.com/riverhohai
    GitHub: https://github.com/hehehai
    CodePen: https://codepen.io/hehehai/

favicon: /favicon.png
logo: /logo.png

# Comment
# e.g disqus: seansun
disqus: false

# e.g
# gitalk:
  # apply: true
  # clientID: clientID
  # clientSecret: clientSecret
  # repo: repo
  # owner: owner
  # admin: admin
gitalk:
  apply: false

# Analytics
# e.g ga: id
ga: false

# Mathjax CDN
# e.g mathjax: true
mathjax: false

# Copyright Infomation
startyear: 2017
