menu:
    Home: /
    Archive: /archives/
    Project: /project/
    About: /about/
    Rss: /atom.xml

social:
    Twitter: https://twitter.com/riverhohai
    GitHub: https://github.com/hehehai
    CodePen: https://codepen.io/hehehai/

favicon: /favicon.png
logo: /logo.png

# Comment
# e.g disqus: seansun
disqus: false

# Analytics
# e.g ga: id
ga: false

# Mathjax CDN
# e.g mathjax: true
mathjax: false

# Copyright Infomation
startyear: 2017
